# Reference here: https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml

Metrics/LineLength:
  Description: 'Limit lines to 165 characters.'
  Enabled: true
  Max: 165

Metrics/MethodLength:
  Description: 'Try to avoid methods longer than 50 lines of code.'
  Enabled: true
  Max: 50

Metrics/ClassLength:
  Description: 'Try to avoid methods longer than 50 lines of code.'
  Enabled: true
  Max: 150

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
